export const SEARCH_VIDEOS = 'SEARCH_VIDEOS';
export const SET_VIDEOS = 'SET_VIDEOS';
export const CONCAT_VIDEOS = 'CONCAT_VIDEOS';
export const SAVE_VIDEO_TO_FAVORITES = 'SAVE_VIDEO_TO_FAVORITES';
export const REMOVE_VIDEO_FROM_FAVORITES = 'REMOVE_VIDEO_FROM_FAVORITES';
export const FETCH_VIDEOS = 'FETCH_VIDEOS'